# Generated by Django 3.2.8 on 2025-11-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counters',
        ),
    ]
